### ISSUE TITLE
Handle transaction with more than 2 accounts

### ISSUE THREAD

**Issue by elkarouh** [epogrebnyak/abacus#55]
In Europe, we have VAT.
So a purchase might involve cash, assets and VAT.
Is it possible to handle it.

By the way, there is a bug in the latest version. 
First 'Logger' is written with cyrillic o instead of latin o.
Second
    logger: Logger = Logger()
should become
    logger: Logger = field(default_factory=Logger)

**Comment by epogrebnyak** [comment]
@elkarouh - thanks for spotting `Logger` problem - now fixed in 0.7.3

purchase with VAT seems a good case for multiple entry - I have it in Python code, not exposed to CLI yet, but easier to do now when `abacus` is migrating to `click` package, 

```
# simple entry
abacus post entry --debit cash --credit equity --amount 1000
# compound entry
abacus post multiple --debit ar 120 --credit vat_incoming 20 --credit sales 100 --credit ar 120 --debit cash 120
# operation
abacus post operation --operation invoice 200 --operation  cost 100
```
 
Does compond entry syntax seem reasonable to you?

**Comment by elkarouh** [comment]
Hi,
Glad you fixed the issue.
Instead of 'multiple', I would rather use 'compound' but this is a matter
of preference.

I don't understand the example you gave (i am no expert in accounting).

abacus post multiple --debit ar 120 --credit vat_incoming 20 --credit
sales 100 --credit ar 120 --debit cash 120

Why do you need --debit ar 120 -credit ar 120 ?
Regards

**Comment by epogrebnyak** [comment]
> Why do you need --debit ar 120 -credit ar 120 ?

I think I was jamming too much into one transaction, this was two things in one:

- (--debit ar 120 --credit vat_incoming 20 --credit sales 100) - this is invoice with VAT (ar is accounts receivable)
- (--credit ar 120 --debit cash 120) - this is accepting payment

Here is a better example: 

```
abacus post compound --debit ar 120 --credit vat_out 20 --credit sales 100 --title "Invoice with VAT 20%"
abacus post single --debit cogs --credit inventory --amount 45 "Register cost of sales"
abacus post single --debit cash --credit cr --amount 80 "Accept payment in cash" --date 2023-10-01
abacus post single --debit cash --credit cr --amount 40 "Accept payment in cash" --date 2023-10-22"
````

It would be nice to share some id across the transactions, for example `abacus event --title "Sales contract #2023-35"
` may issuese some id like `b9fa21`, that can be later referred to by `--event b9fa21` flag. Maybe there is any other strategy to link or relate to four entries above.

I was also thinking about "transaction-based" interface, similar to [medici](https://www.npmjs.com/package/medici#writing-journal-entries) package, it more easier todo it in parogramming interface than CLI though:

```javascript
const journal = await myBook
  .entry("Received payment")
  .debit("Assets:Cash", 1000)
  .credit("Income", 1000, { client: "Joe Blow" })
  .commit();
```

**Comment by epogrebnyak** [comment]
as a note to myself, maybe `abacus post compound --operation cost 45` also viable

**Comment by epogrebnyak** [comment]
@elkarouh - we now have `post-compound`:

```
cx init
abacus chart add --asset cash
abacus chart add --income sales
abacus chart add --liability vat
abacus ledger post-compound --debit cash 120 --credit sales 100 --credit vat 20
abacus report report --trial-balance
```

This results in:

```
            Account            Debit  Credit
asset:cash (Cash).............   120      0
liability:vat (Vat)...........     0     20
income:sales (Sales)..........     0    100
capital:re (Retained earnings)     0      0
```

**Comment by epogrebnyak** [comment]
The example is at https://github.com/epogrebnyak/abacus/blob/main/scripts/vat/vat.sh

I think I shoudl close even though more docs are needed (eg in README)

**Comment by elkarouh** [comment]
Awesome, thanks for the update!

**Comment by elkarouh** [comment]
I just downloaded it.
It seems broken.
You have the same dataclass bug at another place.
In char_command.py:
line 20 and 21 should be:
class ChartCommand(BaseCommand):
    chart: Chart = field(default_factory=Chart)
   
  The example you gave in also broken:
  abacus report report --trial-balance
  should be
  abacus report trial-balance

**Comment by epogrebnyak** [comment]
Strange - tasts do pass and in README there is specifically 'abacus report trial-balance' . Where do you happen to get get example from?

By saying downloaded - are you downloading from pip or from git?

**Comment by epogrebnyak** [comment]
Vat.sh is wrong example, I get it

**Comment by epogrebnyak** [comment]
How does dataclass big manifest? Which python version do you use?

**Comment by epogrebnyak** [comment]
pushed ay some changes in v 0.7.7 - @elkarouh can you please check?

**Comment by elkarouh** [comment]
I get the same dataclass problem at line 20 of chart_command.py. I applied
the same fix again.
I use python 3.11.
I wonder how this works for you because this is not a recent feature.
Regards

**Comment by epogrebnyak** [comment]
https://replit.com/@IevghieniiPogh1/ImpoliteTechnoMosaic#main.sh

In here you could see three comamnds finish up running:

```bash
pip install abacus-py
curl https://raw.githubusercontent.com/epogrebnyak/abacus/main/scripts/vat/vat.sh > vat.sh
source vat.sh
```
in replit - can run `source vat.sh`

**Comment by epogrebnyak** [comment]
@elkarouh, closing for now, please let me know how things work on your side or in replit.
